# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:17
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'get_latest_by': 'name',
                'verbose_name_plural': 'Authors',
                'verbose_name': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN')),
                ('language', models.CharField(blank=True, max_length=100)),
                ('availability', models.BooleanField(default=False)),
                ('status', models.TextField(blank=True)),
                ('number_of_copies', models.IntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barcode')),
                ('authors', models.ManyToManyField(blank=True, related_name='book_author', to='books.Author', verbose_name='Book Authors')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['created'],
                'verbose_name': 'Book',
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('days_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'days_amount',
                'verbose_name_plural': 'Book Types',
                'ordering': ['days_amount'],
                'verbose_name': 'Book Type',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Publication Year')),
                ('publication_place', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'get_latest_by': 'name',
                'verbose_name_plural': 'Publishers',
                'ordering': ['name'],
                'verbose_name': 'Publisher',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_lend_type', to='books.BookType'),
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='book_tag', to='books.Tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_publisher', to='books.Publisher'),
        ),
    ]
